version: '2'
services:
  databases:
    image: mysql
    ports:
      - "9393:9300"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=demodb
  web:
    image: nginx 
